version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: reno_books_db
    environment:
      POSTGRES_DB: reno_books
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d reno_books"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: